apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: a-team-ck
  labels:
    cluster-owner: vfarcic
spec:
  id: a-team-ck
  compositionSelector:
    matchLabels:
      provider: civo
      cluster: ck
  parameters:
    nodeSize: small
    minNodeCount: 1
