apiVersion: devopstoolkitseries.com/v1alpha1
kind: CompositeCluster
metadata:
  name: a-team-eks
  labels:
    cluster-owner: vfarcic
spec:
  id: a-team-eks-no-claim
  compositionRef:
    name: cluster-aws
  parameters:
    nodeSize: medium
    minNodeCount: 3
