#@ load("@ytt:data", "data")
#@ load("@ytt:library", "library")
#@ load("@ytt:template", "template")

#@ resources_lib = library.get("resources")
#@ eks = resources_lib.with_data_values(data.values.eks)

--- #@ template.replace(eks.eval())
