---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  name: silly-demo
spec:
  id: silly-demo
  compositionRef:
    name: app-backend-db
  parameters:
    namespace: a-team
    image: vfarcic/sql-demo:0.1.10
    port: 8080
    host: devops-toolkit.127.0.0.1.nip.io

---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: silly-demo
spec:
  id: silly-demo
  compositionRef:
    name: google-mysql
  parameters:
    version: "8_0"
    size: small
