apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCLCaHcqTbe7nQcdx96XS+lYHlCDZZ98Um9uqJT6YnufHO/bzFChYganOWgwbsMVWg2d+YiUw22KTiLFynuOngQebH85scQetEdMyx86ZvKSr60vJDn2bHbwk1IsGDHbiRfCY6nAnSP3kHTqZwTkxZD4JfH8xl/yXYv2bn4KQBxpry4UN0dmtRVGvaAPkRCP4MRWHOHTiGRokRRs3rXgnwVxb7gRwuwx7BsN2sdUruBL90ZkTSKN2zJWUTyzv7O55RtZqKlDEBTp+VSV1TS3tUCxpoodDQ1ch1UlcD3PzqYe5A0e/Dh3DmOUogxTxFqz0DK/6QPkRjMFeiW33yR3W02CkG/Ab77s2cxxPYUERutn5fjsCXPDvDoXl7AQpG6nfU6UQIpHrMxXFqfzKdFRPHVVap+TjxFGrLs9l175CxkfB1J5TWL/DarSHm7aFrJOnJv/ra7qUPf+45dH3vcnIeBJ2jrjY8YiHYA36O+WiRIQEasfdfJRyiLUISAp34bKp9bLsv4vonGAmUpnMcGKymGZ7cIijSl6CrRxHh1HcDFfQlvhY70HQ6Kt6BwOkdhRXFpAo7188qhyHRPo3taFDbj1d4QjaHAc1EjDNAbDwGOO0CDFJvO42IjefsOt6/e4g6e/I4wJl+S+sze2QWwKXJa6ZB9tMnFiVO5xfFOnA+5OMFaM3/sRDGTWkBcM2CHcmvGhmV8m2AwgNfDDM0ZEv0oTr7qRNuzMuyom18ZVsBnQLKsgBdZeHx5i4VLv4FIuIUL0xZpCL8bwSQmaqWZyq0KwGCyyUBGgo1OW+zHfRy6I+QhdxJUl7GvjqOpOAwPPdjrcnFplTHDTx4XamvPpDDmPQaXtX0=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

