apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgC/FzYrV7AgPHbQlv6Y80sYBPNqPalnoqPJCRjsPrxWybwmctKAfFm3t1NIbB+BsdmNj6QM/QGR+Z/BsEWS2lEreXkvCphmBjy5dClgBYvGhRWQJDwFRTUNiknR9cOY0gnYjfWRNeZ6CMPXfLmGZ1sfI08lMOJmRwf1miSOXP2l3npnuZgkKv+6zgK3rYPzqTBH3S0fIRHADsKny6b7koJQNPK9xqqaqZKLsANL5+yhm87iFpdW3OvTXwzrK9mXZNHrBY6cRcsIIQTvkhiFLROm63104KEpmiri3abez9fbkivAfU7cuDOY4iN1D5ugT6+BZ1V0qu8CtFweEfMn3bbJd0I4T+lT4qFZyDvQv7KoTKMdNdAVe2dX/bKO6+B5g7gPKh4WwxWvI+Mj8WNqSqnGMFF/2gtAxxp8gTIMIqcfPIfY85+zulyjzGtnMGGKp5uyCgLeteemk4ekMhPufGH1pPdOAsTw3DFUwF9g1ytWZ0XJqHWKPuLTgOiDWjvWFdDSgI9+c94Ui11Xuf3IigWquOxm9+hQmDQ4g6Xkbsw7HhTvn/a/RjBTRRmcLbQTR9FJjELzevYeXC0d6SRHukGtwbDrPd67/W0S047y0VZVzGmMIr730D9Zqy6456e20HN/PaiZ42i9h9HvPo/Lomh7jKv2nATvePW16hDMELwmaxebCC1h5BG2fRuJOtYzsGD09P4Gp3XwzGL5+V4r5BqQlUGk3mCeZRK0ZfkPC9SGU5Ijlt9s4yOMwQEmaHNIGmYJEBtFJo4Ky9B5HaG0AREBX07b6992/guV1qDKrDLx9g6s3IvQ09prifWMnw+dQxEZIyf85qMVCV/Eqz8eG2JtBZlnbSw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

