apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgC2EdROFLagX3865L2j7x/JYzJ9WwSMpxStxxlkMZ+s7PAdPuO4Ru2v7QiaQLVSgLziHhPVREziaJ3hDwQ60a4L8P99pzMHY9RR8RHjLa7WryYpxVYqvWCGe8xWUYNE3EcJG8I/xqmC04CISqGx0FrQrKPxAkceKsgHki+iuR/5V+YaP4Dg6KF+OYCCja9pbx0uIgyajP3ekGRYmY9zwVB+wtCAPIfyayLb8SyOKc6xf5UZYzXhYK/uaG+k9/jKd1w5/+4G/3MlYthYHggfcLMZgotJhWqm7kXWMUl7MYcl25QKqaid3icUFD8eZYE9pxZKX6zCCX0JBtHRwiGviQvYX6SLqkJ3cGgDG3wEs/ujERjhiUWf4vvg+ScPwnCDbXBjBQHKt9g6U+mEukcG/jjIAtWwug61AICLy3FxVjwsPGGU7sYVTTFMONCzQq4xvsInMlGUE6Eq+oOJoQKHYwJcPs8qHGWPii+yezMy39dVwDf9OHbEphRVs51s7lMU+qSk0I6JD7NCBkIyje+k7Tgz2m06hsEQmoEPuSSrWGGhD1RaggUPueOROTqLAywkQYXcnkBog9Sa6xxL3E2si/SDcvnbbSW4xU8q+F/ZxtYf2j4MBnOghCRPL5eyXiNQqb7lrEJ9/kxyaKFsnjduD62aU01+UI5yPZiVp/fTTLRXHxHwkuxaLeMLdz8fX5GO5i7qK1wQeI3aGN5ka0BilLgV/TX8YkdO+OpGnILUjG1EocaGVBiigMtMfsZIjSHd6Pk+XbTo01ByeLsmUwhsQ8xsvvCHHhIh1OS8ShgNgpDp2TyIyiOKDUu3QLkafhUWnp8GWXLLxRtyACsZif/dXmja1aHbgrk=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

