apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCcMgWPxHTX5tlv8+uu5T2RNPjJzmeoT98jIQT+TbVf2YKd/RSlyNGuCzWbDJVLJWPmOVdXGHTS3TiF0R/aEPaozF5wCM9OiWzpEhshOy7hYPGDER/Qz0TRSdVjaxFEeYnq7cIqZmOA7Q+GfNwxZ67pAL3VT8x6oqHZ1n+1NcCAtch/JwAgeLmUi7gT/bslnCOPMYvveOUqa5bsSGt1NQ4DAo5LDQy2xqQBVMW/I8JNDHDxXKgFwfvpc5TyLLw+EXBxkH6aAJcOHOI25M5MA9aFrISEksyXi9KwHv4FedRW0df/hUu+a9EZrZM9K6WV2L8BDyOG2Z69pmQCS7tr61oV+/7nrSZCTESnFht2Ooup+i9svLULZRtlH4+hdNPkPElRSUI87k2mQ/8imnp7tcyN4gp8Q2cFsz2VTr5fLrrPSU2hJYYc9myxODYE9pW3fN0mQba6w+A4r/rNKL7hZsmDLmYr/scNkDmizJZaSyTRM5j+DCr5MnMxHGf47zrSpuTYMTt9MpKNma86ZQScNQ6XQTPyGTcpYms9r9SN58BHIz3MoT+ROlnB3PoT/WmVnOTduhCsf54hDs7rNx+ev7385QB9nrAu7gvHw9v9/Sof6sTsrmjay8FGJeVjAisX8kDjoQIOKD3aX7j+DM9odaNne1vpLJaMt2dtvQuO4sNHex0jW3Rp16X/FuSFUEK8ahK75tyR8letOgRItrh8J0UvTajuJvFN19T5xN2fWOB9ANsSvQzpNVtgeV6rJbRcRm0AnkT9QExF5RwitRjJiIPbYjuap+/RCgU6ndBeLVLGvBRf6SRrnpfeTepMv6HtMcIDkzZWJLJLIvmfWxp95q8CSh8Ur/M=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

