apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgB4wlS+YmBSavgb+dgQfJOeYCbJzyykILUF9TfA/zcRpE6VRAS0whhGNWi3/u+mFjd4RA2Tqp0ZLkvz++MDacjKBEMBT92/5RCYN4YiUUURFgkkAlsvK0qGRM84MOPwVCBvgnKDvXE9YHvc+xhmUStipPRNhs94cV/1RakeUEkR9+Gsry++XNltitfh0rZzTlVS8/pyTH/BKqEGDss6nx6rNohQXeQcIG5iscXGBf14jmetIQaXcHus0WT9IiLEEi+pevXWmUxl/LauYS8sL4YA2e9GLnoc6ujGC+GqFKx+a5K4n/MMNmAGs+VzGfnysuVQt6OEqy+YHd9I1QtYIpNcnL5FaMU75ypGEm9nQLH7fHWd+FZS5pZ4FKA8wrbyNTv3HI7WVrDLjg5nrWitlcGsEBEUT54D5hL/Zclxv0rkm4RorDI+6VDbfjTUQj0APINlk4J/8B9n/w9IyoJ4eL7bn73vNpYwGeAzGK6Pvpty7e2qZwWADRjw2tB5EfXF/5ame4SiRZmQclwfBa6QO3mzg/zG/gMZ6rj0+UDA7KIANCzwCO5ig2hE1NC31pogNVlbXPx585b6B1ydM2exwacnMVE7RTBSoWYJ/j9wGWgGn4dDJYBJNfp83BkZI4IJQsLg6/J6zaJPfidWrBVwOC76WP5ChpKpdaCK08pSZRbK5YDN60u6c03xdbEOZHHlFcx9qL8CvexnyW/B7iAhTXfNfdTCjks0LnRzn96xFjn0PayOf+gI219x57WdbPwfRpWx9f7bqwCdyLSEVKmZVJ6F2bakiRUhbfVKEziyEELdfRL18z/EHEk5sF7rXvfAeTRe6y8HMiaRYnINOrQeheJFzTyTTeI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

