apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAk9x31Pe40Q9Y04OjPgO/aubKoWhReIg+pLiiASvZ8IdyZwn55y/pui48aRNEA6c+8qiWMqqXReDYELpbJ+UoDvnkcDkA8Ll/IYNeWGwG0/6ea5Z+eyc6KLSjpSAeXHGoM6L+bmOpJ2REs+NueB9exmrZc3gL8iGWJqkr5qq+sP5SHcyDeHKwiKWtNnvRlKewBviGRcIgED8YH7KxcamfaQluO8J1Wx+1ISNrrdwcXCaoa3igoyjLb/BsOzdNUBCqlxQGnvTC07bMxuCyjjb9rANgP1u206m5syu1IVmcvRZbpHmaPoOqhAm/mv2ovboxMFZVwyMhDRtG+yaZsgRO556d7Xaa0wrX2RYZhscjUertmdL99dGcwYcVK4uOOBFH3bXbbV7Gzhj09zREPdFCCISyp/5Xs4/JCx0p+qMJJPQQHjGKxUV1y80tnr5hyFkAYhvTKdRAvtnKnVv718JcyT4i2uk01mnH4GAgp2dEmvF06lrV90FUgmyhDh9XXQVmzFWaPbdL2qq2Z8/Atg2Ui+T6z62v5ZBYg4Lgo4/Aknl3sTkeAoNfXMJyexK2pYK8DRztxe4KbxsqjdMuKH3e1KdOxNBibP9YDJDayCGZkWuZgalY5TYPvZeOPLBABgKqmRPGkSQ0c9cpSQHdn4BndxT7/+3wsSRuKRvF+Ov+A8l2lrAlF3hoJZPsVUgakBm36l/sgv3CEVQl4uOgbbBxym0OYK/pEtsb5d7V35lmKLrvttxg3cw7EtTmMFD0dtvBGhbSIqWRkgeNurHh6kHzrvEigT3FfvzVk5qnNEsOD4adHMh0BiWqr0urfczH7ahb2f/nXoM6HU5pbXi1YJrGe1qM6SA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

