apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBUA1sJSEenPItiDo5pyjZ+EmVaFJCcqFhBYu+dHErWEEfGQecCxpfKDfjkH+UcEHPDNC93vlQOBfB0t3WGiAHXF7Mz/3WAyYGLnp5ZhndO8qfiiSyF8FG72ekMYErWGtNh2+WiXIMglgM54bj/NTgueVSrClWCFSs6mxIvsYP8pYdHfpYLXbysga/J5uqX20yHfyaKGT1lzZSYLWijyRoc6ONst8oJNTDxMUdH3MeeFspyCQIfGWBRdRxLcjyQ2SCCf0g2E7UBcboTcmHkFq/gDWMIcNZsj3fkriB79hwM2l4TMO1Abu/1oAH+U/lF+H5tx0hPMZJank7P4rik+5NZ/lKi7//SCpPTDxQaPELzV6SPZMgxknxGM97jTPLjiRyNVbRP9+q4OokuK1qMz+mnZHy6Qk7ti2k/Qu65s/6B2PBHG0nPNdfzc1odjqytgnSj/p4W794KDt2u/r9/jb4XVrpX9BdX+2wzE0KxkmIc7lHwu/5QIDS+atZiLpl1xrmZz3suG+cia+SZOAotwhDatXHz8W6d6ITFfhMmtEg2FzDYOqHhZXVTr3kDp+rBiWO8cKgcy1IhZwyhqNCO6HMQMJ3fmnQLHCl3+n0+DTL8rGZVcxvbDq/cJozgfwlG5I508eHf92GRBn8d3Y69m3ITIwaig726C2zAx8X7bSSg7uRQ/ufkvHe3G8UX7RQh/wEPUdV5HLuA0fP/W6Fbj03DHmf/q4E9HUZL0nh0z13V05MtDx2KC3gfn3AA3KqxkH2aoh2Zb30+oSOtYHaTGq3CiY8wCFLMRahI0WJwzXouHXiQnSVJNo/ZcoKSaG4kHPfdj1CEcabsRjSCle+ZwrUDQg8AeUM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

