apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgALIgHmeKXsWv5A6r8xRCVvS3FZbkbLNvm4YrjEovtgNv6J38vbXks+gyokRT5HYtuG855OvymUs34WSpO7IyoA9nmSAnTDdZs1ga5TcuoTOLNFWj7NwFIx9HryfuRBq2jTNXb32DaXkkHOh0bG29xZj7kXZ9ADRs/5Hg+ISLIHjOEY+MQS+Wkqy5BbOyeYvOiVAapHZoLcTJDD+8WXbi0hYby4TDh2DLLQGPossh4//+oLX0nwzIq086oY6kFWmqBun53B+PSoPoWVorqJYIGK13aRvOec0g5PTqPgKXAWmQI7w3QyBGGUy4dDxe/fV0ut9DDLBXzZIwoYRBNmlkfToPRni+nM+F9RoeLJGhHdwN3ejE9/QRtCuSMfWJjTTIdAVx67Sck2+iRmS2jLEOf1A5Hr5ugY8YjYiE0wDND+H9ZVo2dkR0JUKISbSr8ROjUkWjb8iWw+YEBTUrROxo6V8i68XSrfJIlDtLZIMpljXKizoAboFM5LzDKunmDb3Vi8FbpD+lMFG7dFh9AsRC85Imo888HxUcwUC60PQEgTsCbC+4o41eZecC2DTu2MVMM0jVnO9pAH1fJhEt4ea1t6CAJaWOayvROl58bbLALmIAEoOUhHKEOpVW5X4K5ftW7M4SOUKd9dcQWA7/2L428q1vyXq4+SnXsnpDqC+4sNdd5NEqVLv5NRoqtBb+YpMrYSzKq7miFD8T08pXsyDqhbxbYMiGQZGwh3XRmNWZgDI/90F6tURj10nUmqsRFgUO59i4Y+D6bOv+p8SEheZ20RU7CSRgC3cvPfXJx+hCB3vrEvRr20Soh8uQEndLYLnBkldj/PqRRZkkqhGULZFipUGDgI9VM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

