apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCBKx5CxmTp5/02lqHyil9LkNYOVCrHTQjbnYGQn+mYQicSOyDGM9HL9xzqoDka1L4S+bNgFdPi+C/OqHgEAC83/7umOqgyjNrxS3NvTxCJA1BsfYrweGnhf+VaqFsBlSdtyV2l3lE6B292IglCUNfulWHhChSKmVzxMZWwj5xOkE69wrfPUoTQqh7QxujZ+OMN4QXXGpG47KBj7hO4EhPFFhUjhqX4bBBpfm7FL+Bpyqu+RBqDE+GVEbI+fATt0d7k6cfabCHmzK4jvstgoMx0aUK41W9JKehUDGK4AQclNBTGbm6IfsHAMx6vKdaK8a449bpBwD1/ABpukWWfDCBSSb4O8uL0yGggrk6VTGvXebulOJHjrEVGLG6C5HBViEfu1fa2GUS8SxuXGtIOu3sfjYFwSqtn6pFC3zYqmiL/ovMEJXyOaz4RxCtWG1EUmfqKWutjyJx3xtqejGFNc3g55o18LluNGMZO/op86u1z+IYp9hDZt/XfOL3Y58jQA8svR9nULy9bPS4NJDdmLDBylbZ3AycheDqGbQiTAUR1QUj1+oFVsvC/LOePB7orph4mJBhgom3J29Z9V+PwTEe52xf4P9Hl+yNOXHJnR/KTK2a+A9zNMySniCHUVWidbBXrRZ5DM/sqd7orHY0fIwG37zqBOIRhCiSwPlo6p8xLBVCqjhOE54s44zm1NhVI6irQ89Uj9pddmduwQpxJHQnkmEuJuvXzAHJjmYju/bb62FrjUHq/qDiwa6Ke1oxH/yymALnOdpcgoC8w3JnwMYtbznfkpleMDGkENiKZkHgWMtwvUH93lZmxDrBVIuKh4BI/qh00lv1DvuH2fXojUQU3YL02LhM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

