apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAxAIlFNb4qBtOzXch0FuVXM8r7nzi1mzzL+esavvbCwXJXBZv9iWW1Vt4hSoqeZC5niSUD++/Ljp64wyhnCAEWtkLmsG14QDbGpLrCT/UST1BBsiSJNsEYN+m4l0zXV1W687Jouj0/5IHZBHi6X3ufQ2CRAQwrQa3bWIkgnf+d4Khy9zFwsjfn47GBe90quHmYg4gSZqyvcmxk10e71SLYqrbhbFVYkaeNVkefWUADCE79nA9+1j4UUA8mpRR4VLxK7wlQ49uQ5MRJxe0qUfBJRHZYA6kd7RcKvK/M+tf297S/Kn5s8iq7sbS1oEMju4HPfZ3Q8acTOscjXp/dRc3nak/ZgagYJc4JqsQ/KjcC3MiHu88vGvCBGUoSD2FAzz9VDdOc0mC4c+gFS+spT+i7PVSuIJMT9w5UOpciApGrgvZJEpPUH6yfHWoGsykgWgK38AlOE7byWpxEQKoBU8UvLwggImbsYUD1RhWXzjRVezCK+emXoywmkQ+OygT/rrjFM6YunVCQW28BY+sKnvY4Jft5JTZbHgAHj/GuStLnfdMqIWEUj3TtkV29kNfO79OMZloOf7A9aezHDJX2z9NEpU8o7To0a2Oz94KGy6wiB+/AZjYXXXrrslNlp9FYqFaRyMmEiRnroGEcN8R5AYvNN1bSqSXlB8pHptH5JAdOnPEHkFPFO5LZ2CJz99G6rg9ovyKhB3ciIxYvVZYgOgiURzefSbQfLMqmhXWYWtb4zsBhuBUY5uXL6U48YUxLIEaqssnVTZ0qJ1w5/0C1ML7ps/MDKIQRRTlYg4e9l7l2DDgqD8ny1GXsvDQdrowOAd77JdleIlytVD9EwCqRXLLjJR1bJAw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

