apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgByBxA+TRWr1QtI5ZWrwYeCAsMW+bVsPBaDkjZQ+iBu5JRnkavba687xP+fso0eFw32Ip/JrjKj5eBfHx3MPfe2RNynXoEkDa+5dqki/W9i1dbnrVb+60Czm3GQ6jplXvybxy/BwDpFtr2pXPGdfMmKoR33wutkua6QKNLaJVp3GDWAD2raexj2mUAUZphe3hrbwWjdjRkjMBtXWfWld95vPB6pzOKxC5GNKpbXnO6nC2Iekq0dOdh83SCHblsjj7mR2UxZqQ6IeAfVFp8QlqYOlxzwqBPca3C5t/mwUuepDYTZriJMbhh0LifL+B64wkUnswgklO5/PDPod1QHaQJvQhspTm4aiyoTbOvud3fvDmVYcAwO1CjlxW9J30nAa9ooTGXI2+LUuRA6pQH/tzpzQKkYOz3hVT2dYColM/WVhsAdVGJnfjW17Durl8nehrXzi4RIgl0yDczkMpMY62v89srIdcl8DzoFgeirWFXMS4KltMkjuICbQYgVslaVg+sHRaXY3EzMrHltdlGQHGZHK+B7wOOkKpeUQ/UQWlCP2vn4dSEYyZ751ltxVycz4N1LPDi+cGZ7UPVWOc/eWWtwhBHWLGPbwtKufgfcfIswFB8icgHvsQmcSGZmxQEXg6rwnMwMMIOq14L52utZGmQSNbz6QEH2qW4wN7iRHhkOpm5f0JTztP3Xn0p9k28feCFJrhIZ+zPOy4a2hL79VSY5g4r3u2jzpPeJCSQsuyotGkCEWpNai3X3wcrjPmcPf8S4hcI4YaYwBBUxuky6d1t6GKxE+VQDvMgGERW2z7uK0+ZWrsVSztKn//eitsVEhSmdaUN4nJURy+TqJnwG701leeWeEG0=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

