apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAGDGG4kYEzJxzAxfYEt0xWwRkFa88Gm6kUN/2LIF5b/JgTnv2L/e3gf7ObBYaQ3Tjh5pOglAeO5SwiUW5zTu3bND91BTOoEU53o2+Nto++6rE+g9Q2WLurd4IfvfHDQBWYFUAPccnQb4NoBxTxJkLD1cx/je4OOgsQQlFXauymkwxKy1ak6UvV2WnOckr5WQyeNGsdqsWYHjU78bdlbsN1vn1e0h6J1jgucCYT/2/JH1t+p2dQGPvyFLBSVl5KXHb8KAgH7UeGSPxeG0ZO3nfP+Q7XJig2V6ySYVp+Oo8rwzn0spx2KmgKLVcQN9HnE+DFxe3UmE7PDj6JpdfR8ttytXCFcCXs5F9Dkh7qeAS0Y3SzfjXG6j2snqLX0E6scs9wE9TwO+b8cVt3IbdrHwir7qRxBYFHp7n0LKVkHKHXL/1/9ek9n5FOyllmoDduUKJoglaji4EoriPfeNMCgUqsoEG9nKl5ZXnoBSCoq5Jhw183pIceXQcs4XqJbiod9rE9PfuSJ0m3PE2NU8BBxOZlzTtSakAJ9E0vS8JlR5JRqdeusC382voofkOxrZI5OPlvrq/kWc4aUs64X2KomQM8yoYisNx82nw7IFIRPt3wwhXcexCtm+GaD9lpw5Z5R7wQuOgrJ6+SMkeGkVLB3urw7TvSOLfXfNJ2C4R57uMO7siLQ3Tjs0iu/02KYmBqJU2DjxdhC6zSnLmpR6/ADl59JpC/zp08VBzD9cYVoM2XzXdP+3PsC41OF2b58T/ES7JyytClwQ6s6VvB/ylAN3HKy2kZjv86bF54Tyoq+/VRZ1ZlzGjft0nkWKsXNgUs6t3bltXBR29vgsOpop8o33QlKqg+0rQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

