apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCJ5XVXVXjeLgIFUWsQzNshCDsKZfkwdciw3ErKZU4wEedFeZ5mpHzZrJFZ4u8v4RFFPk3RDkRaLrTP3J9uxkKIi8ItoSfYLw5i3ZItidTs48DJ+NMD1Eg25F2V0z/mXxA/0wO9O7nkPB8SFeGjCSy+nvToXCueN45S57o6waOrMV8mEYe0HGTThRf7g5m+EzArGuCrcl4wm0OSu8Ux6AQxdpRzntZMTKtVQdTR/JssA/52BE6Xn1dJj3EKDsqt2PX5MQCjDx9kfryctS3NDFlH3HxOuzklIGkGvvnS8ZZoyREuijIthpWbqq6MA0HILGA7DTDnRW3a+KFHUCydvAts2ZLQLzdLcsLzpkYrtG80YcuT+KmdemYOeAdfW7JY8UVGE4LvOYd+RE+YITmwhrRq2AiNBmcHR6nsQnvqkpLj1S3z9KE0oMjeYsUiG+dVU7qWmCGN+YEkqQbWbGWo1jVneeizQ2g2HdqkdPVY2tZlG6gHP0yY+MYl9/NEqd9DSDPKH7/SOpHT/JYqOMJVPVwhPLLzJNctM/aXHZxcrqvKY6++2nkkKyVkr8e0daMeKETTwQ6PiseJAUg077sqjIEoaKp0SJzyGxpHYGarJcryMOeitSWAv9WHHhOJBzYa4LmqtKBirRX71o92rBL9uKzDZvoaq3jTLj1rMYnuyNgV5xHsgnfWuzQbUPVxhqkXpHlQo7mYarC0GwnVaVZmIUQxov10N4RbCnQv/7Alsz0NLrITNc/BNAoxP1NO6k1oMocUu5hgNTZOz+VzJga770wsCqnRhJg2y2ONXm0wDJ82ZGWuuSPDrl8MGx1jplf/aW3Jhp5wz8hRsY8x5n1GCHieVuKSzNM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

