apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCeAFvz0Il48xm2065l+N4zheG5cq62PaPnPeCaWddPcEO8aWWcZ2Rb9uTOYwiubTCXM6Rlg37u79j7xTL3riZQDMjSVocHxSad1yo1ZdUekSbDnAQTYrY8eiyNjBZdsoqHoLFk6QxY27JBPtyBEdh5DOtBHmafKJIAP+GEwf2QdynHHBmd6eVSXE/qlYfA3ki+HfhY6lvSaE+xedGTp5BWrAjceBZV8q4PJYtTTdnXbx0JPL/0DrBGCpeZWjCj94KWx+2daxJjbU84eJiSwU0n0V58wyA7a0zXlgqrHs3N+fvl406OZ7xs9fMwl/dDWoAdTAnGC5bVrtGmSFhuDmLjQ980MiScQfdL8lFSJByA9ln7xskv7slBnEgZPyI/dRZqefNwMP/CSQ0oNJWWNQV8QEnKuSOCnR3w8dwaqWuyW2JWqW2oCUnFTns2jmGZpnPuC6sknV93w6tuRX4QHoiQEXbsZKuuPNwra0P1BGN2jVvuTvAyETM0M9EtKTmS8KXyNJ7TdFyExi8MlFrqayq3gVUFr50oCIbZkAbceu3ubBmxAW8qTSbZsduDy7llP+g5myQVQgeQXDcUhjfq5aLHCLqqCrKXu+UyIY33Hdo/e2ozdGNqA3xlohzqu6r+44Huam3Pvx0Hc8B6THc/zDvPlgE4agZgItD6OSCKteGkpAc77etgC/z4KpjqrXVwD/HIweGx94Pykfa2dVJaOwTENpLEHp/Uwq8GvF+ETNqOnpryg5N+1EesihiqkhAYd/tgF0QWgX66O1uYBmGgyHofyPKHNhxh6roSVK1Jh3EZ1wmMh9awHhApAlBZyjCCUBQytZWv0sBXy3vcZpzzZUB/GBk8jXk=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

