apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: civo-creds
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgCt0fYreCSQze+LhpjexbmCtURMXzliEQ45xEhT6X9s9y8g3+luXY1FrlZvH6fb37/5yMIulk9eltDBmQWUWBYzZO0uwRYkucVbYrkMfK5EBi/yARQl9bYw18Hq5Lj9Zh/wxt7U7I1J+T3+qr6l52QNK0AUVF3TZkIvW7qmXPyQRyjOW9oF1wFpSVLf4txhc9ce292s2AfiNmOQWW4dKeWyrvEchsnSqck1vSpb5rVxHVhLUqGPxYJ5/v8nAlNhEIGREAEhGBAojnt6UwSAAHeCuLIdmOayvJqQ0Ox1aau8xseeNGNJcJiLB/AexV7liUX62HB6huYzNpC8jww6yg3tpRJ3tgkwndUdriGMTc5Z9kP7bJqQuUWXKCaY0Qc2+MET+SPhAFtxSTTifRWi7sHWaLauP3JEG3FrqXLhrtAuNIaNUeawnRqCzgUSrxWGi7OV62gvyCF9fZzry+05Jtg8GeRkELDqi62nIrGVEp4q+q9kxORxCEJ/bbQNsr2BMyl6iCljAU0b4/HqBCvfyI+MZ1aoPT0cBinIVDE9clF+RJfJ9d1bc9SW6SSp5Ecm+BaYfS4SL75wVv+XnQJwy8Bj0KOPrBb0uK+ogJBbXVUfpBYvTpGaTG79iTiWiMPzaC6yBCTJO0cJks0JYXLpfNlZL2u06HZghWFnd4SaMjrfG2OtqzlAcEtMDnrweswT7/hc6eb88OMUICrU4jJV7HgSjLy9wLAKiu7K0DyZgoFrqci4okM7YL/67W1pisJgHB/LOg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: civo-creds
      namespace: crossplane-system

